WireServerEndpoint changes
Azure/azure-linux-extensions pull request #1207
Opened 2020-09-25 23:32 UTC by Jyotsna-Anand

2020-09-26 00:05 UTC, ejarvi requested changes

2020-09-26 00:05 UTC, ejarvi commented on VMEncryption/main/EncryptionSettingsUtil.py
> +		wireserver_endpoint_file = '/var/lib/waagent/WireServerEndpoint'
would be cleaner to define this in Common.py alongside the wire server IP constant

2020-09-26 00:05 UTC, ejarvi commented on VMEncryption/main/Common.py
> +	wireserverIP = "168.63.129.16"
maybe call this static_wireserver_ip to differentiate it from the dynamic one

2020-09-26 00:05 UTC, ejarvi commented on VMEncryption/main/EncryptionSettingsUtil.py
> +            self.logger.log("Using static wireServerIP from CommonVariables")
indentation

2020-09-26 00:11 UTC, ejarvi commented on VMEncryption/main/EncryptionSettingsUtil.py
> +		wireserver_endpoint = "http://" + wireserverIP + ":80/machine?comp=diskEncryptionData"
maybe this format string (that ends in ":80/machine?comp=diskEncryptionData") can be a constant in Common.py as well

2020-09-29 17:09 UTC, Jyotsna-Anand commented on VMEncryption/main/Common.py
> +	wireserverIP = "168.63.129.16"
Addressed review comments in commit 21ba15.

2020-09-29 17:10 UTC, Jyotsna-Anand commented
This PR was created for an initial review until access to azure-linux-extensions repo could be got. 
Moving this PR to a new branch under "azure-linux-extensions" repo.
https://github.com/Azure/azure-linux-extensions/pull/1209

2020-09-29 17:10 UTC, closed without merging