Ensure Metric watcher is always running
Azure/azure-linux-extensions pull request #1475
Opened 2022-01-10 22:40 UTC by simathih

2022-01-10 23:00 UTC, hestolz requested changes
as-is seems like this will error out, unless i'm missing something. did this pass testing?

2022-01-10 23:07 UTC, thperapp commented on AzureMonitorAgent/agent.py
> +    if (protected_settings is None or len(protected_settings) == 0) or (public_settings is not None and "proxy" in public_settings and "mode" in public_settings.get("proxy") and public_settings.get("
nit: public_settings["proxy"] and public_settings["proxy"]["mode"] might be better for readability

2022-01-10 23:17 UTC, simathih commented on AzureMonitorAgent/agent.py
> +    if (protected_settings is None or len(protected_settings) == 0) or (public_settings is not None and "proxy" in public_settings and "mode" in public_settings.get("proxy") and public_settings.get("
fixed

2022-01-11 02:10 UTC, hestolz reviewed
if enable fails later on, will the metrics proc be left alive on the machine?

2022-01-11 02:13 UTC, simathih commented on AzureMonitorAgent/agent.py
> +    if (protected_settings is None or len(protected_settings) == 0) or (public_settings is not None and "proxy" in public_settings and "mode" in public_settings.get("proxy") and public_settings.get("
We have to test this once the build is done

2022-01-11 02:25 UTC, hestolz approved these changes

2022-01-11 02:47 UTC, simathih commented
> if enable fails later on, will the metrics proc be left alive on the machine?

yeah, but this is by design...subsequent update would call disable() before removing the bad AMA install which would clean up the process

2022-01-11 02:48 UTC, merged