Pankajjoshi/data disk encryption for cvm test release
Azure/azure-linux-extensions pull request #1726
Opened 2023-05-31 09:27 UTC by pankajosh

updated for release, and correction

2023-06-02 18:11 UTC, pankajosh commented on VMEncryption/volume-notif-svc/azure-diskencryption-vol-notif.service
> +MemoryMax=50MB
it should be 50M instead of 50 MB

2023-06-03 02:45 UTC, canfikret requested changes

2023-06-05 18:59 UTC, canfikret requested changes

2023-06-06 17:43 UTC, pankajosh commented on VMEncryption/volume-notif-svc/UdevVolNotif.c
> +#define LOG_DIRETORY "/tmp"
agree. done

2023-06-07 07:58 UTC, canfikret requested changes

2023-06-07 07:58 UTC, canfikret commented on VMEncryption/volume-notif-svc/UdevVolNotif.c
if the partition is formatted as ext4; but not added for /etc/fstab yet due to a race; ADE is started by VNS; however, the partition is skipped as there is no mount point.

I think we should have mnt_monitor() as well to cover that scenario.

2023-06-15 01:22 UTC, canfikret requested changes

2023-06-15 01:22 UTC, canfikret commented on VMEncryption/volume-notif-svc/UdevVolNotif.c
> +}
Here's a sample how to enlist the ext4 volumes that doesn't have a mapper.

https://github.com/canfikret/linux/blob/main/mount/mnt_entries_thread.cpp

2023-06-15 01:42 UTC, canfikret requested changes

2023-06-15 01:42 UTC, canfikret commented on VMEncryption/volume-notif-svc/UdevVolNotif.c
Take a look at this example: https://github.com/canfikret/linux/blob/main/mount/mnt_monitor.cpp

2023-06-21 05:43 UTC, canfikret requested changes

2023-06-21 05:43 UTC, canfikret commented on VMEncryption/main/check_util.py
> +            msg='Identity used in VM can not do wrapKey/unwrapKey operations.'
Suggestion: "The managed identity provided in public settings is not correct or not authorized to do secure key release operation in your key vault/HSM. Please verify and re-run ADE install after fixing the issue"

2023-06-28 18:02 UTC, canfikret requested changes

2023-06-28 18:02 UTC, canfikret commented on VMEncryption/main/CryptMountConfigUtil.py
> +            with open("/etc/crypttab", "a") as wf:
let's make sure the encoding is ASCII.

2023-06-28 18:02 UTC, canfikret commented on VMEncryption/main/CryptMountConfigUtil.py
> +            with open("/etc/crypttab", "a") as wf:
Also, the permissions need to be set to 644

2023-06-28 18:02 UTC, canfikret commented on VMEncryption/volume-notif-svc/azure-diskencryption-vol-notif.service
> +#MemoryMax=50M
Let's put a comment that the workingset of ADE is added to the service because it is run a child process. Hence, we don't want to add a limit here.

2023-06-30 00:29 UTC, canfikret commented on VMEncryption/volume-notif-svc/UdevVolNotif.c
> +                if(             strcmp(it.syspath.c_str(),syspath)==0 &&
In a subsequent, non-edit PR, run document formatter for fixing the syntax consistency issues.

2023-06-30 00:30 UTC, canfikret approved these changes

2023-06-30 15:34 UTC, canfikret approved these changes

2023-06-30 18:28 UTC, canfikret approved these changes

2023-06-30 18:37 UTC, merged