remove python-future from oms extension
Azure/azure-linux-extensions pull request #1765
Opened 2023-07-20 22:13 UTC by NarineM

This PR covers removal of 3rd party urllib dependency PythonCharmers that triggered s360 security bugs. We ll' be using python2 standard libs such as urllib and urlparse APIs moving forward.
Unit tested by mocking extension calls with distros running python v3.8.10, python 2.7.5.

2023-08-23 21:26 UTC, simathih commented
is the usage impact only in the extension code for OMS? how will we test impact across various python versions? could this affect our install/enable telemetry?

2023-08-23 21:27 UTC, simathih requested changes
how will we test impact across various python versions?

2023-08-28 06:01 UTC, NarineM commented
@simathih it was tested with 2 major versions of python (See the PR descriptions). We will need to run E2E tests across distro matrix in Canary as this change impacts extension code which is hard to test via mock testing. Yes, it can potentially impact SLA not only telemetry, as it is used for example to reitrieve resource info from metadata API: https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/omsagent.py#L570
It is large chunk of change and needs to be tested E2E.

2023-09-11 17:13 UTC, simathih approved these changes

2023-09-15 23:29 UTC, jscalev approved these changes

2023-09-19 02:43 UTC, merged