Remove output of unnecessary mdsd.err messages to extension status
Azure/azure-linux-extensions pull request #1813
Opened 2023-10-03 22:02 UTC by aswatt

This line would send mdsd.err logs to the Azure extension status message in the portal if new ones were found while LAD was running successfully. However, this was leading to noise from the customer's perspective - they were seeing error messages output even when provisioning succeeded. Specifically, there was one transient situation where we'd fail initially but succeed on a retry during initial startup, and the logs output to mdsd.err on the initial failure were causing red herrings.

This removes updating the status message in Azure Portal with these log messages, to minimize confusion as to if LAD is running successfully or not.

2023-10-05 21:43 UTC, Dmitry-Matveev commented on Diagnostic/diagnostic.py
> -        hutil.do_status_report(g_ext_op_type, "success", '1',
We'd need someone with knowledge of the original intent to comment on reporting errors with "success" demarkation and what scenarios we are going to lose by fully cutting it out if any at all.

If we learn we are OK to cut it out without degrading any of the supported scenarios, we should be goog to go. If not - we can complicate this change a little by only skipping known false-positives like "table already exists".

2023-11-08 17:37 UTC, AaronRM commented on Diagnostic/diagnostic.py
> -                               "message in mdsd.err:" + str(last_error_time) + ":" + last_error)
Could we instead do a more targeted fix that logs 409 errors from Azure Storage in this scenario as info/warning instead?

2023-11-08 17:37 UTC, AaronRM requested changes
:clock1:

2023-11-08 21:44 UTC, aswatt commented
Going for a more targeted fix to change the specific expected error messages to be warnings instead, closing out this PR.

2023-11-08 21:44 UTC, closed without merging