Add arm64 support for amaca
Azure/azure-linux-extensions pull request #1999
Opened 2024-11-23 02:26 UTC by thperapp

2024-11-25 23:46 UTC, simathih approved these changes

2024-11-26 22:32 UTC, simathih approved these changes

2024-11-26 22:32 UTC, simathih commented on AzureMonitorAgent/packaging.sh
> +# if [[ $uncompressed_size -gt $max_uncompressed_size ]]; then
should we maybe still log the warning though without failing?

2024-12-04 23:32 UTC, simathih approved these changes

2024-12-10 21:24 UTC, simathih approved these changes

2025-03-06 02:48 UTC, AaronRM requested changes

2025-03-06 02:48 UTC, AaronRM commented on AzureMonitorAgent/agent.py
> +    if current_arch == 'x86_64':
Use a switch block here instead of if/else.

2025-03-06 02:48 UTC, AaronRM commented on AzureMonitorAgent/agent.py
> +        liblz4x64_bin_local_path = os.getcwd() + "/amaCoreAgentBin/liblz4x64.so"
No lz4 for arm64?

2025-03-06 03:09 UTC, thperapp commented on AzureMonitorAgent/agent.py
> +        liblz4x64_bin_local_path = os.getcwd() + "/amaCoreAgentBin/liblz4x64.so"
nope. Confirmed with Kennedy that they drop down to gzip for ARM64 right now.

2025-03-06 03:11 UTC, thperapp commented on AzureMonitorAgent/agent.py
> +    if current_arch == 'x86_64':
match case (python's version of switch block) will break py2 support iirc :(

2025-03-06 17:11 UTC, AaronRM approved these changes

2025-03-06 17:34 UTC, merged